version: "3"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
  web:
    build: .
    container_name: web
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "80"
    volumes:
      - ".:/code"
    restart: always